#!/bin/bash

README_PATH="docs/Home.md"
MAIN_PATH="docs/README.md"

if [[ -f "$MAIN_PATH" ]]; then
  mv "$MAIN_PATH" "$README_PATH"
  echo "Replaced $README_PATH with $MAIN_PATH"
else
  echo "Error: $MAIN_PATH does not exist. Commit aborted."
  exit 1
fi

git add "$README_PATH"
