#!/bin/bash

README_PATH="docs/Home.md"
MAIN_PATH="docs/README.md"

if [[ -f "$MAIN_PATH" ]]; then
  mv "$MAIN_PATH" "$README_PATH" || true
  echo "Replaced $README_PATH with $MAIN_PATH"
  git add "$README_PATH"
else
  echo "$MAIN_PATH does not exist. Pre-Commit aborted."
fi