name: Deploy

on:
  workflow_run:
    workflows: ["Docker"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Create inventory file
        run: |
          mkdir -p ansible
          echo "[servers]" > ansible/inventory
          echo "server ansible_host=${{ secrets.SERVER_HOST }} ansible_user=${{ secrets.SERVER_USERNAME }}" >> ansible/inventory

      - name: Create Ansible playbook
        run: |
          cat > ansible/deploy.yml << 'EOF'
          ---
          - name: Deploy application
            hosts: servers
            become: yes
            tasks:
              - name: Install required system packages
                apt:
                  name:
                    - docker.io
                    - make
                  state: present
                  update_cache: yes

              - name: Create .env file
                copy:
                  dest: /root/.env
                  content: |
                    GH_TOKEN=${{ secrets.GH_TOKEN }}
                    OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
                    OPENROUTER_API_KEY=${{ secrets.OPENROUTER_API_KEY }}
                    NPM_TOKEN=${{ secrets.NPM_TOKEN }}
                    TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
                    TELEGRAM_CI_ID=${{ secrets.TELEGRAM_CI_ID }}
                    NODE_ENV=production

              - name: Login to GitHub Container Registry
                docker_login:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

              - name: Pull Docker image
                docker_container:
                  name: ai-node-boilerplate
                  image: ghcr.io/javeoff/ai-node-boilerplate:main
                  state: started
                  restart: yes
                  pull: yes
                  env_file: /root/.env
                  ports:
                    - "3000:3000"
          EOF

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Run Ansible playbook
        run: |
          ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i ansible/inventory ansible/deploy.yml
