name: Deploy

permissions:
  contents: read
  packages: write
  actions: read
  deployments: write

on:
  workflow_run:
    workflows: ["Docker"]
    types:
      - completed
  workflow_dispatch:

env:
  NODE_ENV: production
  CONTAINER_NAME: ai-node-boilerplate
  IMAGE_NAME: ghcr.io/javeoff/ai-node-boilerplate
  PORT: 3000

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Ansible and GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y ansible
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y

      - name: Login to GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Create inventory file
        run: |
          mkdir -p ansible
          echo "[servers]" > ansible/inventory
          echo "server ansible_host=${{ secrets.SERVER_HOST }} ansible_user=${{ secrets.SERVER_USERNAME }}" >> ansible/inventory

      - name: Create Ansible playbook
        run: |
          cat > ansible/deploy.yml << 'EOF'
          ---
          - name: Deploy application
            hosts: servers
            become: yes
            vars:
              node_env: ${{ env.NODE_ENV }}
              container_name: ${{ env.CONTAINER_NAME }}
              image_name: ${{ env.IMAGE_NAME }}
              port: ${{ env.PORT }}
            tasks:
              - name: Install required system packages
                apt:
                  name:
                    - docker.io
                    - make
                  state: present
                  update_cache: yes

              - name: Create .env file
                shell: bash
                run: |
                  # Get all environment variables from GitHub and create .env file
                  gh api /repos/${{ github.repository }}/environments/production/variables --jq '.variables | to_entries | .[] | .key + "=" + .value' > /root/.env
                  
                  # Add secrets (they are stored separately from variables)
                  gh api /repos/${{ github.repository }}/actions/secrets --jq '.secrets | .[] | .name' | while read secret; do
                    echo "${secret}=${{ secrets[secret] }}" >> /root/.env
                  done
                  
                  # Add local env variables from workflow
                  echo "NODE_ENV={{ node_env }}" >> /root/.env
                  echo "CONTAINER_NAME={{ container_name }}" >> /root/.env
                  echo "IMAGE_NAME={{ image_name }}" >> /root/.env
                  echo "PORT={{ port }}" >> /root/.env

              - name: Login to GitHub Container Registry
                docker_login:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

              - name: Pull Docker image
                docker_container:
                  name: "{{ container_name }}"
                  image: "{{ image_name }}:main"
                  state: started
                  restart: yes
                  pull: yes
                  env_file: /root/.env
                  ports:
                    - "{{ port }}:{{ port }}"
          EOF

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Run Ansible playbook
        run: |
          ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i ansible/inventory ansible/deploy.yml
