name: Generate Project Tasks
on:
  workflow_dispatch: # Для ручного запуска

permissions:
  issues: write
  contents: read

jobs:
  generate-tasks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate tasks using Aider
        id: aider
        uses: javeoff/aider-github-actions/ask@main
        with:
          model: openrouter/anthropic/claude-3.5-sonnet
          prompt: |
            Изучи код проекта и предложи список из 5-10 задач для улучшения и новых функций.
            Каждую задачу начни с номера и точки (например "1.", "2." и т.д.).
            Каждая задача должна быть конкретной и реализуемой.
            Опиши каждую задачу в 1-2 предложениях.
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

      - name: Create GitHub Issues
        uses: actions/github-script@v7
        with:
          script: |
            const aiderOutput = `${{ steps.aider.outputs.response }}`;
            
            // Ищем задачи по шаблону "число. текст"
            const tasks = aiderOutput.match(/\d+\.\s+[^\n]+/g);
            
            if (!tasks) {
              console.log('No tasks found in the output');
              return;
            }
            
            for (const task of tasks) {
              const taskText = task.replace(/^\d+\.\s+/, ''); // Убираем номер в начале
              
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: taskText,
                body: `Generated by Aider\n\nOriginal task: ${task}`,
                labels: ['enhancement']
              });
              
              console.log(`Created issue: ${taskText}`);
            }
