name: Generate Project Tasks
on:
  workflow_dispatch: # Manual trigger

permissions:
  issues: write
  contents: write

jobs:
  generate-tasks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate tasks using Aider
        id: aider
        uses: mirrajabi/aider-github-action@main
        timeout-minutes: 10
        with:
          model: openrouter/anthropic/claude-3.5-sonnet
          aider_args: '--chat-mode ask --yes --message "Analyze the project code and suggest 5-10 tasks for improvements and new features. Start each task with a number and dot (e.g. \"1.\", \"2.\" etc.). Each task should be specific and implementable. Describe each task in 1-2 sentences."'
          openai_api_key: ${{ secrets.openai_api_key }}
          anthropic_api_key: ${{ secrets.anthropic_api_key }}
          cohere_api_key: ${{ secrets.cohere_api_key }}
          deepseek_api_key: ${{ secrets.deepseek_api_key }}
          gemini_api_key: ${{ secrets.gemini_api_key }}
          groq_api_key: ${{ secrets.groq_api_key }}
          openrouter_api_key: ${{ secrets.openrouter_api_key }}

      - name: Create GitHub Issues
        uses: actions/github-script@v7
        with:
          script: |
            const aiderOutput = process.env.AIDER_OUTPUT;
            
            // Look for tasks matching pattern "number. text" or "number text"
            const tasks = aiderOutput.match(/\d+\.?\s+[^\n]+/g);
            
            if (!tasks) {
              console.log('No tasks found in the output');
              return;
            }
            
            for (const task of tasks) {
              const taskText = task.replace(/^\d+\.?\s+/, ''); // Remove number prefix (with or without dot)
              
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: taskText,
                body: `Generated by Aider\n\nOriginal task: ${task}`,
                labels: ['enhancement']
              });
              
              console.log(`Created issue: ${taskText}`);
            }
        env:
          AIDER_OUTPUT: ${{ steps.aider.outputs.response }}
