name: Update Wiki

# on: [push]

# recommended
on:
  push:
    branches: [main]
    paths:
      - docs/**
      - README.md
concurrency:
  group: publish-wiki
  cancel-in-progress: true
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: ineshbose/wiki-action@v1
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          WIKI_DIR: 'docs'
          AUTO_SIDEBAR: true